name: CI workflow for SSE Lecture

on: [push, ]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "install black"
        run: python -m pip install black
      - name: "Run black"
        run: black --check *.py

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "install pytest"
        run: python -m pip install pytest


